spring:
  application:
    name: eureka-peer

server:
  port: 10000

eureka:
  instance:
    hostname: prod
    instance-id: prod
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10000/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 10000